apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
  labels:
    app: resources-pod
spec:
  containers:
    - name: resources-container
      image: kaizernurik/hw2mlops:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      env:
      - name: MLOPS_HW2_MODEL_FILE_ID
        value: "1B1BvfrkKKimI0kTxYVgXwOMG3zHhsptC"
      resources:
        requests:
            memory: "500Mi"
            cpu: 1
        limits:
            memory: "1024Mi"
            cpu: 1