apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment-blue-green
  labels:
    app: simple-deployment-blue-green
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: simple-container
  template:
    metadata:
      name: simple-container
      labels:
        app: simple-container
    spec:
      containers:
        - name: simple-container
          image: kaizernurik/hw2mlops:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
          - name: MLOPS_HW2_MODEL_FILE_ID
            value: "1B1BvfrkKKimI0kTxYVgXwOMG3zHhsptC"

