apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    app: simple-pod
spec:
  containers:
    - name: simple-container
      image: kaizernurik/hw2mlops:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8000
      env:
      - name: MLOPS_HW2_MODEL_FILE_ID
        value: "1B1BvfrkKKimI0kTxYVgXwOMG3zHhsptC"
