on: push
jobs:
  build:
    name: ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Linter
        run: flake8 --ignore=E501,W291,E226,W504 ./ 
      - name: Tests
        run: python -m pytest tests
        run: python -m ml_example.tests.train
